language: python
python:
  - "3.10"
dist: jammy

services:
  - docker

before_script:
  - sudo apt-get install build-essential libssl-dev libffi-dev python3-dev
  - pip install --upgrade setuptools
  - pip install MarkupSafe
  - pip install --no-binary :all: MarkupSafe
  - pip install docker-compose

script:
  - docker-compose up -d

after_script:
  - docker-compose down
