language: python
python:
  - "3.10"
dist: jammy

services:
  - docker

before_install:
  - eval "$(ssh-agent -s)"
  - echo "$PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - echo -e "Host 159.203.99.44\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

script:
  - ls
  - scp -o StrictHostKeyChecking=no -r / poliuser@159.203.99.44:/home/poliuser/PoliBot
  - ssh poliuser@159.203.99.44 'cd /home/poliuser/Polibot && ./deploy_script.sh'
