language: python
python:
  - "3.10"
dist: jammy

services:
  - docker

before_script:
  - eval "$(ssh-agent -s)"
  - ssh-add


script:
  - ls
  - docker-compose up -d
  - scp -o StrictHostKeyChecking=no -r / poliuser@159.203.99.44:/home/poliuser/PoliBot
  - ssh poliuser@159.203.99.44 'cd /home/poliuser/Polibot && ./deploy_script.sh'
