language: python
python:
  - "3.10"
dist: jammy

services:
  - docker

before_install:
  - sudo apt-get install -y sshpass
  - echo -e "Host 159.203.99.44\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

script:
  - ls
  - sshpass -p "$PRIVATE_KEY" scp -o StrictHostKeyChecking=no -r ./ poliuser@159.203.99.44:/home/poliuser/PoliBot/
  - sshpass -p "$PRIVATE_KEY" ssh poliuser@159.203.99.44 'cd /home/poliuser/PoliBot && ./deploy_script.sh'
